language: python
jobs:
  include:
    - name: 'Python 2.7 + 3.4-3.9 + nightly on Xenial Linux'
      python:
        - 2.7
        - 3.4
        - 3.5
        - 3.6
        - 3.7
        - 3.8
        - 3.9
        - nightly
    - name: 'Python 3.7.4 on macOS'
      os: osx
      osx_image: xcode11.2
      language: shell
    - name: 'Python 3.8.0 on Windows'
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
install:
  - pip install -r requirements.txt
# command to run tests
script: pytest